version: 2.1

orbs:
  redmine-plugin: agileware-jp/redmine-plugin@0.0.22

workflows:
  version: 2
  test:
    jobs:
      - redmine-plugin/download:
          redmine_version: trunk
      - redmine-plugin/test:
          name: trunk-pg
          executor: redmine-plugin/ruby-pg
          requires: [redmine-plugin/download]
      - redmine-plugin/test:
          name: trunk-mysql
          executor: redmine-plugin/ruby-mysql
          requires: [redmine-plugin/download]
      - redmine-plugin/test:
          name: trunk-sqlite3
          executor: redmine-plugin/ruby-sqlite3
          requires: [redmine-plugin/download]
