version: 2.1

orbs:
  redmine-plugin: agileware-jp/redmine-plugin@0.0.22

workflows:
  version: 2
  test:
    jobs:
      - redmine-plugin/download:
          name: download-trunk
          redmine_version: trunk
      - redmine-plugin/download:
          name: download-4.0
          redmine_version: 4.0.5
      - redmine-plugin/download:
          name: download-3.4
          redmine_version: 3.4.12
