version: 2.1

orbs:
  redmine-plugin: agileware-jp/redmine-plugin@0.0.22

workflows:
  version: 2
  test:
    jobs:
      - redmine-plugin/download:
          redmine_version: trunk
      - redmine-plugin/test:
          name: trunk-26-pg
          executor: redmine-plugin/ruby-26-pg
          requires: [redmine-plugin/download]
      - redmine-plugin/test:
          name: trunk-25-pg
          executor: redmine-plugin/ruby-26-pg
          requires: [redmine-plugin/download]
      - redmine-plugin/test:
          name: trunk-24-pg
          executor: redmine-plugin/ruby-24-pg
          requires: [redmine-plugin/download]
      - redmine-plugin/test:
          name: trunk-23-pg
          executor: redmine-plugin/ruby-23-pg
          requires: [redmine-plugin/download]
