version: 2.1

orbs:
  redmine: agileware-jp/redmine-plugin@0.0.22

workflows:
  version: 2
  test:
    jobs:
      - redmine/download:
          redmine_version: trunk
      - redmine/test:
          executor: redmine/ruby-pg
          requires: [redmine/download]
